# --- TWOJE AKTUALNE USTAWIENIA ---
CONFIG_ZMK_USB_LOGGING=y
CONFIG_ZMK_POINTING=y

# --- USTAWIENIA DLA DONGLA (I STABILNOŚCI) ---
# Zwiększenie mocy Bluetooth dla lepszego zasięgu do dongla
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# Lepsza stabilność połączenia
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Zgłaszanie poziomu baterii połówek przez dongle do systemu
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
